spring:
  application:
    name: auth-service

  cloud:
    config:
      fail-fast: true
      password: ${CONFIG_SERVICE_PASSWORD}
      username: user

  web:
    resources:
      static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,/classpath:/public/,classpath:/WEB-INF/

auth:
  secret:
    path: ./.keys

---
spring:
  config:
    import: optional:configserver:http://config:8888
    activate:
      on-profile: docker
  cloud:
    config:
      uri: http://config:8888
---
spring:
  config:
    import: optional:configserver:http://localhost:8888
    activate:
      on-profile: local
  cloud:
    config:
      uri: http://localhost:8888