spring:
  application:
    name: auth-service

  liquibase:
    change-log: classpath:/changelog/db.changelog-master.xml
    enabled: true

  cloud:
    config:
      uri: http://localhost:8888
      fail-fast: true
      password: ${CONFIG_SERVICE_PASSWORD}
      username: user
  config:
    import: configserver:http://localhost:8888