spring:
  application:
    name: account-personal-service
  cloud:
    config:
      fail-fast: true
      password: ${CONFIG_SERVICE_PASSWORD}
      username: user

bank:
  bik: 96754

---
spring:
  config:
    import: optional:configserver:http://config:8888
    activate:
      on-profile: docker
  cloud:
    config:
      uri: http://config:8888
---
spring:
  config:
    import: optional:configserver:http://localhost:8888
    activate:
      on-profile: local
  cloud:
    config:
      uri: http://localhost:8888