version: '3.7'
services:
  grafana:
    build: './monitoring/grafana'
    ports:
      - "3000:3088"
    volumes:
      - ./grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus:/prometheus

  rabbitmq:
    ports:
      - "5672:5672"

  config:
    build: config-service
    ports:
      - "8888:8888"

  registry:
    build: registry-service

  gateway:
    build: gateway-service

  auth-service:
    build: auth-service

  users-service:
    build: users-service
    ports:
      - "5001:5001"

  account-business-service:
    build: account-business-service
    ports:
      - "6002:6002"

  account-personal-service:
    build: account-personal-service
    ports:
      - "6003:6003"

  transaction-service:
    build: transaction-service
    ports:
      - "6001:6001"

  info-business-service:
    build: info-business-service
    ports:
      - "6005:6005"

  info-personal-service:
    build: info-personal-service
    ports:
      - "6004:6004"

  payment-service:
    build: payment-service
    ports:
      - "6006:6006"