version: '3.7'
services:


  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - "15672:15672"
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  config:
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
      IP_DB: $IP_DB
      DB_PASSWORD: $DB_PASSWORD
    image: makuni/apelsin-config:latest
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  registry:
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
      IP_DB: $IP_DB
      DB_PASSWORD: $DB_PASSWORD
    image: makuni/apelsin-registry:latest
    restart: always
    ports:
      - "8761:8761"
    depends_on:
      - config
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  gateway:
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
      IP_DB: $IP_DB
      DB_PASSWORD: $DB_PASSWORD
    image: makuni/apelsin-gateway:latest
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - config
      - registry
      - account-personal-service
      - account-business-service
      - info-personal-service
      - info-business-service
      - auth-service
      - users-service
      - payment-service
      - transaction-service
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  auth-service:
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
      TRANSACTION_SERVICE_PASSWORD: $TRANSACTION_SERVICE_PASSWORD
      AUTH_SERVICE_PASSWORD: $AUTH_SERVICE_PASSWORD
      USERS_SERVICE_PASSWORD: $USERS_SERVICE_PASSWORD
      INFO_PERSONAL_SERVICE_PASSWORD: $INFO_PERSONAL_SERVICE_PASSWORD
      ACCOUNT_BUSINESS_SERVICE_PASSWORD: $ACCOUNT_BUSINESS_SERVICE_PASSWORD
      ACCOUNT_PERSONAL_SERVICE_PASSWORD: $ACCOUNT_PERSONAL_SERVICE_PASSWORD
      INFO_BUSINESS_SERVICE_PASSWORD: $INFO_BUSINESS_SERVICE_PASSWORD
      AUTH_SHA_SALT: $AUTH_SHA_SALT
      PAYMENT_SERVICE_PASSWORD: $PAYMENT_SERVICE_PASSWORD
      IP_DB: $IP_DB
      DB_PASSWORD: $DB_PASSWORD
    image: makuni/apelsin-auth-service:latest
    restart: always
    healthcheck:
      test: "curl -f http://localhost:5000/actuator/health || exit 1"
      interval: 30s
      timeout: 60s
      retries: 50
    depends_on:
      - config
      - registry
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    ports:
      - "5000:5000"

  users-service:
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
      USERS_SERVICE_PASSWORD: $USERS_SERVICE_PASSWORD
      AUTH_SHA_SALT: $AUTH_SHA_SALT
      IP_DB: $IP_DB
      DB_PASSWORD: $DB_PASSWORD
    image: makuni/apelsin-users-service:latest
    restart: always
    depends_on:
      auth-service:
        condition: service_healthy
      config:
        condition: service_started
      registry:
        condition: service_started
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  account-business-service:
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
      ACCOUNT_BUSINESS_SERVICE_PASSWORD: $ACCOUNT_BUSINESS_SERVICE_PASSWORD
      IP_DB: $IP_DB
      DB_PASSWORD: $DB_PASSWORD
    image: makuni/apelsin-account-business-service:latest
    restart: always
    depends_on:
      auth-service:
        condition: service_healthy
      config:
        condition: service_started
      registry:
        condition: service_started
      rabbitmq:
        condition: service_started
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  account-personal-service:
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
      ACCOUNT_PERSONAL_SERVICE_PASSWORD: $ACCOUNT_PERSONAL_SERVICE_PASSWORD
      IP_DB: $IP_DB
      DB_PASSWORD: $DB_PASSWORD
    image: makuni/apelsin-account-personal-service:latest
    restart: always
    depends_on:
      auth-service:
        condition: service_healthy
      config:
        condition: service_started
      registry:
        condition: service_started
      rabbitmq:
        condition: service_started
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  transaction-service:
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
      TRANSACTION_SERVICE_PASSWORD: $TRANSACTION_SERVICE_PASSWORD
      IP_DB: $IP_DB
      DB_PASSWORD: $DB_PASSWORD
    image: makuni/apelsin-transaction-service:latest
    restart: always
    depends_on:
      auth-service:
        condition: service_healthy
      config:
        condition: service_started
      registry:
        condition: service_started
      rabbitmq:
        condition: service_started
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  info-business-service:
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
      INFO_BUSINESS_SERVICE_PASSWORD: $INFO_BUSINESS_SERVICE_PASSWORD
      IP_DB: $IP_DB
      DB_PASSWORD: $DB_PASSWORD
    image: makuni/apelsin-info-business-service:latest
    restart: always
    depends_on:
      auth-service:
        condition: service_healthy
      config:
        condition: service_started
      registry:
        condition: service_started
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  info-personal-service:
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
      INFO_PERSONAL_SERVICE_PASSWORD: $INFO_PERSONAL_SERVICE_PASSWORD
      IP_DB: $IP_DB
      DB_PASSWORD: $DB_PASSWORD
    image: makuni/apelsin-info-personal-service:latest
    restart: always
    depends_on:
      auth-service:
        condition: service_healthy
      config:
        condition: service_started
      registry:
        condition: service_started
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  payment-service:
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
      PAYMENT_SERVICE_PASSWORD: $PAYMENT_SERVICE_PASSWORD
      IP_DB: $IP_DB
      DB_PASSWORD: $DB_PASSWORD
    image: makuni/apelsin-payment-service:latest
    restart: always
    depends_on:
      auth-service:
        condition: service_healthy
      config:
        condition: service_started
      registry:
        condition: service_started
      rabbitmq:
        condition: service_started
    logging:
      options:
        max-size: "10m"
        max-file: "10"