spring:
  application:
    name: transaction-service

  datasource:
    url: jdbc:postgresql://192.168.1.102:5432/maxbank-transactions
    username: maxbank-transactions
    password: maxbank-transactions
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: create

server:
  port: 3900

bank:
  bik: 96754
