spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: users-service
  cloud:
    config:
      fail-fast: true
      password: ${CONFIG_SERVICE_PASSWORD}
      username: user

  mail:
    host: smtp.yandex.ru
    port: 465
    username: apelsin.pay@yandex.ru
    password: oebhtkhnbpewynnq
    properties:
      mail:
        smtp:
          ssl:
            enable: true
          auth: true
          starttls:
            enable: true

---
spring:
  config:
    import: optional:configserver:http://config:8888
    activate:
      on-profile: docker
  cloud:
    config:
      uri: http://config:8888
---
spring:
  config:
    import: optional:configserver:http://localhost:8888
    activate:
      on-profile: local
  cloud:
    config:
      uri: http://localhost:8888
