spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: info-business-service
  cloud:
    config:
      uri: http://localhost:8888
      fail-fast: true
      password: ${CONFIG_SERVICE_PASSWORD}
      username: user
  config:
    import: configserver:http://localhost:8888
