@startuml
!include <cloudinsight/tomcat>
!include <cloudinsight/kafka>
!include <cloudinsight/java>
!include <cloudinsight/postgresql>
!include <cloudinsight/rabbitmq>
!include <cloudinsight/docker>
!include <cloudinsight/nodejs>
!include <cloudinsight/nginx>
!include <cloudinsight/linux>

title __Архитектура приложения__
 left to right direction

person "Клиент" as client

rectangle "<$linux>\nUbuntu server" {
    node "<$nginx>\nNginx" as nginx_main
    rectangle "<$docker>\nDocker" {
        node "Контейнеры back-end сервисов" as backend
        node "Контейнеры front-end сервисов" as frontend
    }
}



node "<$postgresql>\nPostgreSQL Server" as db

client <--> nginx_main
nginx_main <--> backend
nginx_main <--> frontend
backend <--> db

@enduml