@startuml
title Авторизация\n
autonumber 1
"Пользователь" as p -> "Веб-приложение" as js : Запросить форму входа
activate p
activate js
js --> p : Показать форму входа
deactivate js
loop "Пока нет успеха авторизации"
    p -> p: Заполнение логина и пароля
    p -> js: Передача логина и пароля
    deactivate p
    activate js
    js -> "Сервер" as s: Передача логина и
    deactivate js
    activate s
    s -> s: Проверка логина и пароля
    alt Логин и пароль верные
        s -> s: Генерация ключей
        s --> js: Ключи для входа
        activate js
        js --> p: Сообщение об успехе авторизации
        js -> js: Сохранение ключей авторизации
        js -> js: Переход на главную страницу
    else Логин и пароль неверные
        s --> js: Ошибка авторизации
        deactivate s
        js --> p: Сообщение об ошибке авторизации
        deactivate js
    end
end
@enduml