@startuml
title Авторизация\n
autonumber 1
"Пользователь" as p -> "Клиент-приложение" as js : Войти
activate js
js -> p : Переадерсация пользователя на\nавторизационный сервис\nна специальный URL
deactivate js
activate p
p -> "Авторизационный\nсервер" as auth : Переадресация
deactivate p
activate auth
loop "Пока неверные логин и пароль"
    auth --> p: Показ формы входа по логину и паролю
    deactivate auth
    activate p
    p -> auth : Логин и пароль
    deactivate p
    activate auth
    auth -> auth : Проверка логина и пароля
end
auth -> auth: Генерация кода
auth -> js : Код авторизации
deactivate auth
activate js
js -> auth : Код авторизации
deactivate js
activate auth
auth -> auth : Генерация ключей\nдоступа пользователя
auth --> js : Ключи доступа пользователя
deactivate auth
activate js
js -> : Доступ к защищенным ресурсам для пользователя
@enduml