@startuml
title Оплата\n
autonumber 1
actor "Клиент" as p
p -> "Сайт компании" as c ++: Нажатие кнопки\n"Оплатить через Апельсин pay"

c -> "Система" as sys ++: Создать заказ
sys --> c --: URL оплаты, куда необходимо\nперенаправить пользователя
c --> p --++: URL оплаты
p -> sys ++: Запрос страницы оплаты по URL оплаты
sys --> p: Отображение страницы оплаты
p -> p : Выбор способа оплаты
alt Оплата через Апельсин pay
    p -> sys: Нажатие кнопки "Оплатить через Апельсин pay"
    opt Если пользователь не авторизован в Апельсин pay
       p -> sys: Ввод логина и пароля
       sys -> sys: Проверка авторизации
       sys --> p: выдача ключей
    end
    sys --> p: Отображение доступных счетов пользователя
    p -> sys: Выбранный счет для оплаты
    sys -> sys: Создание транзакции\nс внутренним отправителем и\nвнутренним получателем\nс типом "Оплата"
    ...Ожидаем выполнение взаимодействия транзакции...
else Оплата через Тинькофф
    p -> sys: Нажатие кнопки "Оплатить через Tinkoff"
    sys -> sys: Создание транзакции\nс отправителем - Тинькофф и\nвнутренним получателем\nс типом "Оплата"
    ...Ожидаем выполнение взаимодействия транзакции...
end

sys -> sys: Сообщение, что деньги на счете получателя заморожены
sys --> p: URL для перенаправления\nпосле оплаты
p -> c --: Переход по URL перенаправления\nпосле успешной оплаты
c -> sys: Запрос статуса оплаты
sys --> c: Статус оплаты

alt Сайт компании хочет отменить оплату
    c ->> sys: Отменить оплату
        c -> p: Сообщение об отмене оплаты
    sys -> sys: Отмена транзакции
    ...Ждем отмены транзакции...
else alt Сайт компании хочет подтвердить оплату
    c ->> sys: Подтвердить оплату
        c -> p: Сообщение о подтверждении оплаты
    sys -> sys: Разморозка денег у транзакции
    ...Ждем разморозки транзакции...
end
@enduml