@startuml
title Транзакция\n
autonumber 1
actor "Клиент" as p
p -> "Система" as sys : Открыть транзакцию
activate sys
sys --> p : Id транзакции
alt Внутренний отправитель
    sys -> sys: Начислить комиссию за снятие
    sys -> sys: Проверка отправителя
    sys -> sys: Снятие денег со счета отправителя
else Отправитель - Тинькофф
    sys --> "Тинькофф API" as t --++: Запросить оплату пользователя с возвратом на redirect_url
    t -> sys --++: Url оплаты и id оплаты
    sys -> p --++: Редирект на адрес url оплаты от Тинькофф
    p -> p : Ввод платежных данных
    p -> t --++: Нажатие кнопки "Оплатить"
    t --> sys --++: Перенаправление на адрес redirect_url
    sys -> t ++: Запрос статуса оплаты
    t --> sys --: Статус оплаты
end

alt Внутренний получатель
    sys -> sys: Готовность к начислению
    sys -> sys: Проверка получателя
    sys -> sys: Начисление денег на счет получателя
    opt Необходимость заморозить деньги у получателя
        sys -> sys: Заморозить деньги на счету получателя
        ...Ожидаем сообщение о разморозке средств...
        sys -> sys: Разморожены деньги у получателя
    end
else Внешний получатель
    sys -> t: Запросить выплату на банковский счет
    t --> sys: id выплаты
end

sys -> sys: Завершение транзакции

opt Отправитель - Тинькофф
    sys ->> t ++: Подтверждение оплаты
    deactivate t
end


@enduml