security:
  oauth2:
    client:
      clientId: account-business-service
      clientSecret: ${ACCOUNT_BUSINESS_SERVICE_PASSWORD}
      grant-type: client_credentials
      scope: server,info_b_s

spring:
  application:
    name: account-business-service

  datasource:
    url: jdbc:postgresql://${IP_DB}:${PORT_DB}/maxbank-transactions
    username: maxbank-transactions
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: update


server:
  port: 6002

feign:
  hystrix:
    enabled: true