security:
  oauth2:
    client:
      clientId: account-service
      clientSecret: ${ACCOUNT_SERVICE_PASSWORD}
      accessTokenUri: http://localhost:5000/auth/oauth/token
      grant-type: client_credentials
      scope: server

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/maxbank-users
    username: maxbank-users
    password: maxbank-users
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: auto

server:
  servlet:
    context-path: /info
  port: 6000


feign:
  hystrix:
    enabled: true