security:
  oauth2:
    client:
      clientId: account-personal-service
      clientSecret: ${ACCOUNT_PERSONAL_SERVICE_PASSWORD}
      grant-type: client_credentials
      scope: transaction,server

spring:
  application:
    name: account-personal-service

  datasource:
    url: jdbc:postgresql://${IP_DB}:5432/maxbank-transactions
    username: maxbank-transactions
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: update


server:
  port: 6003

feign:
  hystrix:
    enabled: true