spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/maxbank-users
    username: maxbank-users
    password: maxbank-users
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: update

server:
  port: 5000

encoder:
  sha512:
    salt: ${AUTH_SHA_SALT}

security:
  oauth2:
    client:
      clientId: auth-service
      clientSecret: ${AUTH_SERVICE_PASSWORD}
      accessTokenUri: http://localhost:5000/oauth/token
      grant-type: client_credentials
      scope: server,info_b_s,info_p_s