security:
  oauth2:
    client:
      clientId: deposit-service
      clientSecret: ${DEPOSIT_SERVICE_PASSWORD}
      accessTokenUri: http://localhost:5000/auth/oauth/token
      grant-type: client_credentials
      scope: edit_money,server

spring:
  application:
    name: deposit-service

  datasource:
    url: jdbc:postgresql://localhost:5432/maxbank-transactions
    username: maxbank-transactions
    password: maxbank-transactions
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: update


server:
  servlet:
    context-path: /deposit
  port: 6003

feign:
  hystrix:
    enabled: true