server:
  port: 8080
#  ssl:
#    key-store: classpath:keystore.p12
#    key-store-password: qwerty
#    key-alias: test_key
#    key-store-type: PKCS12

spring:
  webflux:
    static-path-pattern: /static/**
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowed-headers: "*"
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
          include-expression: serviceId.endsWith('-SERVICE')
          url-expression: "'lb:http://'+serviceId"

#logging:
#  level:
#    org.springframework.cloud.gateway.handler.RoutePredicateHandlerMapping: debug