security:
  oauth2:
    client:
      clientId: info-business-service
      clientSecret: ${INFO_BUSINESS_SERVICE_PASSWORD}
      grant-type: client_credentials
      scope: server

spring:
  application:
    name: info-business-service

  datasource:
    url: jdbc:postgresql://192.168.3.121:5432/info-business
    username: info-business
    password: info-business
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: update


server:
  port: 6005

feign:
  hystrix:
    enabled: true