security:
  oauth2:
    client:
      clientId: info-personal-service
      clientSecret: ${INFO_PERSONAL_SERVICE_PASSWORD}
      grant-type: client_credentials
      scope: server,users_s

spring:
  application:
    name: info-personal-service

  datasource:
    url: jdbc:postgresql://${IP_DB}:${PORT_DB}/info-personal
    username: info-personal
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: update


server:
  port: 6004

feign:
  hystrix:
    enabled: true