security:
  oauth2:
    client:
      clientId: payment-service
      clientSecret: ${PAYMENT_SERVICE_PASSWORD}
      accessTokenUri: http://localhost:5000/oauth/token
      grant-type: client_credentials
      scope: server,account_b_s,info_b_s,transaction_s

spring:
  application:
    name: payment-service

  datasource:
    url: jdbc:postgresql://localhost:5432/apelsin-payment
    username: apelsin-payment
    password: apelsin-payment
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: update

pay:
  url: https://redirect.ru/

server:
  port: 6006