security:
  oauth2:
    client:
      clientId: payment-service
      clientSecret: ${PAYMENT_SERVICE_PASSWORD}
      grant-type: client_credentials
      scope: server,account_b_s,info_b_s,transaction_s

spring:
  application:
    name: payment-service

  datasource:
    url: jdbc:postgresql://${IP_DB}:5432/apelsin-payment
    username: apelsin-payment
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: update

server:
  port: 6006

---
spring:
  config:
    activate:
      on-profile: docker

pay:
  main:
    url: http://payment.pshiblo.xyz/
  internal:
    url: http://payment.pshiblo.xyz/tinkoff/success

---
spring:
  config:
    activate:
      on-profile: local

pay:
  main:
    url: http://localhost:3006/
  internal:
    url: http://localhost:3006/tinkoff/success