security:
  oauth2:
    client:
      clientId: transaction-service
      clientSecret: ${TRANSACTION_SERVICE_PASSWORD}
      grant-type: client_credentials
      scope: server,account_b_s,account_p_s

spring:
  application:
    name: transaction-service

  datasource:
    url: jdbc:postgresql://${IP_DB}:${PORT_DB}/maxbank-transactions
    username: maxbank-transactions
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: update


apelsin:
  account:
    number: 12345678900987654321

pay:
  tinkoff:
    url: ${PAY_INTERNAL}

server:
  port: 6001