spring:
  datasource:
    url: jdbc:postgresql://${IP_DB}:5432/maxbank-users
    username: maxbank-users
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: update

server:
  port: 5001

encoder:
  sha512:
    salt: ${AUTH_SHA_SALT}

security:
  oauth2:
    client:
      clientId: users-service
      clientSecret: ${USERS_SERVICE_PASSWORD}
      grant-type: client_credentials
      scope: server