FROM adoptopenjdk:11-jre-hotspot
MAINTAINER Maxim Pshiblo <pshblo.max@gmail.com>

ARG JAR_FILE=./target/info-personal-service-1.0.jar

COPY ${JAR_FILE} /app.jar

CMD ["java", "-Xmx300m", "-Dspring.profiles.active=docker", "-jar", "/app.jar"]

EXPOSE 6004